### ISSUE TITLE
Update license to MIT

### ISSUE THREAD

**Issue by icogn** [zsrtp/Randomizer-Web-Generator#41]
You are tagged in this issue because you have contributed to the Randomizer-Web-Generator project.

We would like to update the license for this project to MIT (currently the license is not specified).

If you are comfortable with this change, please leave a comment of "I agree to share all my contributions to the Randomizer-Web-Generator under MIT" or something similar.

Once everyone has agreed, we will update the license of this project.

@lunarsoap5 @Luzagar @Chris-Is-Awesome @Zushi11

**Comment by icogn** [comment]
I agree to share all my contributions to the Randomizer-Web-Generator under MIT.

**Comment by lunarsoap5** [comment]
I agree to share all my contributions to the Randomizer-Web-Generator under MIT

**Comment by Chris-Is-Awesome** [comment]
I agree to share all my contributions to the Randomizer-Web-Generator under MIT

**Comment by Zushi11** [comment]
I agree to share all my contributions to the Randomizer-Web-Generator under MIT

**Comment by Luzagar** [comment]
I agree to share all my contributions to the Randomizer-Web-Generator under MIT

**Comment by lunarsoap5** [comment]
All consents submitted. Closing issue and merging https://github.com/zsrtp/Randomizer-Web-Generator/pull/42 to update repository license.
